- name: conditions demo
  hosts: local
  connections: local
  vars:
    number: 76
  tasks: 
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug: 
      msg: "given number {{ number }} is less than or equal to 100"
    when: number < 100

  - name: print if the number is greater than or equal to 100
    ansible.builtin.debug: 
      msg: "given number {{ number }} is greater than or equal to 100"
    when: number > 100  