- name: datatypes
  hosts: local
  connection: local
  vars:
    duration: 120 # number
    course: devops # string
    is_live: true #boolean
    tools: #list []
    - linux
    - shell
    - ansible
    concepts: #map or dictionary or object referd by {}
      ci: jenkins
      script: "shell, ansible, terraform, python"
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "course {{course}}, time {{ duration }}, is live {{ true }}, tools {{ tools }}, concepts are {{ concepts }} "