- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt: 
  - name: username
    prompt: please enter your 
    private: true

  - name: password
    prompt: please enter your 
    private: true
  tasks: 
  - name: print user information
    ansible.builtin.debug:
      msg: "hello user {{ username }}, password is {{ password }}"
