- name: play level variables
  hosts: local
  connection: local
  vars_files: 
  - course.yaml
  tasks: 
  - name: print course information
    ansible.builtin.debug:
    #vars reference should be surrounded by ""
      msg: "hi {{ course }} time {{ duration }} trained by {{ trainer }}"
